//
//  SecondRouter.swift
//  CleanSwift
//
//  Created by Phạm Thanh Hải on 28/11/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Lee Nguyen Templates which motivated by CleanSwift templates so
//  you can apply clean architecture to your iOS and Mac projects,

import UIKit

protocol SecondProtocol: SecondDataPassing {
    var viewController: SecondViewController? {get}
    func doSomething()
    func dissmissVC()
}

protocol SecondDataPassing
{
  var dataStore: SecondDataStore? { get }
}

class SecondRouter: SecondProtocol, SecondDataPassing
{
  weak var viewController: SecondViewController?
  var dataStore: SecondDataStore?
    
    init(viewController: SecondViewController?) {
        self.viewController = viewController
    }
    
    deinit {
        print("SecondRouter \(#function)")
    }
    
    
    func doSomething() {
        
    }
    
    func dissmissVC() {
        self.viewController?.dismiss(animated: true)
    }
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: SecondViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: SecondDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
