//
//  SecondPresenter.swift
//  CleanSwift
//
//  Created by Phạm Thanh Hải on 28/11/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Lee Nguyen Templates which motivated by CleanSwift templates so
//  you can apply clean architecture to your iOS and Mac projects,

import UIKit

protocol SecondPresenterInput: SecondInteractorOutput {
    
}

protocol SecondPresenterOutput: AnyObject {
    func displaySomething()
    func displayLanguageList(listArr: [String])
    func closeVC()
}


final class SecondPresenter {
    private(set) weak var output: SecondPresenterOutput!
    
    // MARK: - Initializers
    
    init(output: SecondPresenterOutput) {
        self.output = output
    }
    
    deinit {
        print("SecondPresenterOutput \(#function)")
    }
}

// MARK: - ScheduleDetailsPresenterInput

extension SecondPresenter: SecondPresenterInput {
    func presentSomething() {
        
    }
    
    func presentListArr(arrList: [String]) {
        self.output.displayLanguageList(listArr: arrList)
    }
    
    func presentCloseVC() {
        self.output.closeVC()
    }
}
