//
//  FirstConfigurator.swift
//  CleanSwift
//
//  Created by Phạm Thanh Hải on 28/11/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//  This file was generated by Lee Nguyen Templates which motivated by CleanSwift templates so
//  you can apply clean architecture to your iOS and Mac projects,
import UIKit

class FirstConfigurator
{
    // MARK: - Singleton

    static let sharedInstance: FirstConfigurator = FirstConfigurator()
    
    init() {
        
    }
    
    deinit {
        print("FirstConfigurator \(#function)")
    }

    // MARK: - Configuration

    func configure(viewController: FirstViewController) {

        let router = FirstRouter(viewController: viewController)
        let presenter = FirstPresenter(output: viewController)
        let interactor = FirstInteractor(output: presenter)
        
        router.dataStore = interactor
        viewController.output = interactor
        viewController.router = router
    }
  
}
