//
//  FirstPresenter.swift
//  CleanSwift
//
//  Created by Phạm Thanh Hải on 28/11/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Lee Nguyen Templates which motivated by CleanSwift templates so
//  you can apply clean architecture to your iOS and Mac projects,

import UIKit

protocol FirstPresenterInput: FirstInteractorOutput {
    
}

protocol FirstPresenterOutput: AnyObject {
    func displaySomething()
    func displayText(text: String)
    func displayLang(firstLang: String, secondLang: String)
    func displayLangChoosed(lang: String, label: UILabel)
}


final class FirstPresenter {
    private(set) weak var output: FirstPresenterOutput!
    
    // MARK: - Initializers
    
    init(output: FirstPresenterOutput) {
        self.output = output
    }
    
    deinit {
        print("FirstPresenterOutput \(#function)")
    }
}

// MARK: - ScheduleDetailsPresenterInput

extension FirstPresenter: FirstPresenterInput {
    func presentSomething() {
        
    }
    
    func presentText(text: String) {
        self.output.displayText(text: text)
    }
    
    func presentSwapLang(firstLang: String, secondLang: String) {
        self.output.displayLang(firstLang: firstLang, secondLang: secondLang)
    }
    
    func presentChoosedLang(lang: String, label: UILabel) {
        self.output.displayLangChoosed(lang: lang, label: label)
    }
}
