//
//  FirstWorker.swift
//  CleanSwift
//
//  Created by Phạm Thanh Hải on 28/11/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Lee Nguyen Templates which motivated by CleanSwift templates so
//  you can apply clean architecture to your iOS and Mac projects

import Foundation

class FirstWorker
{
    func doSomeWork()
    {
    }
    
    func getTextResultFromAPI(text: String, s: String, t: String, onCompletion: @escaping (String?) -> Void){
        let urlString = "http://home1.tranducanh.com/translate/api.php?msg=\(text)&s=\(s)&t=\(t)"
        guard let url = URL(string: urlString) else {
            print("URL không hợp lệ")
            return
        }
        
        // Tạo yêu cầu HTTP
        let task = URLSession.shared.dataTask(with: url) { (data, response, error) in
            if let error = error {
                print("Error: \(error.localizedDescription)")
                onCompletion(nil)
                return
            }
            
            if let httpResponse = response as? HTTPURLResponse, (200...299).contains(httpResponse.statusCode) {
                if let data = data {
                    do {
                        let decoder = JSONDecoder()
                        let translationResult = try decoder.decode(TextEntity.self, from: data)
                        let result = translationResult.result
                        onCompletion(result)
                    } catch {
                        print("Error decoding JSON: \(error.localizedDescription)")
                        onCompletion(nil)
                    }
                } else {
                    onCompletion(nil)
                }
            } else {
                print("Invalid HTTP response")
                onCompletion(nil)
            }
        }

        task.resume()
    }
}
