//
//  TestPresenter.swift
//  CleanSwift
//
//  Created by Phạm Thanh Hải on 10/9/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Lee Nguyen Templates which motivated by CleanSwift templates so
//  you can apply clean architecture to your iOS and Mac projects,

import UIKit

protocol TestPresenterInput: TestInteractorOutput {
    
}

protocol TestPresenterOutput: AnyObject {
    func displaySomething()
}


final class TestPresenter {
    private(set) weak var output: TestPresenterOutput!
    
    // MARK: - Initializers
    
    init(output: TestPresenterOutput) {
        self.output = output
    }
    
    deinit {
        print("TestPresenterOutput \(#function)")
    }
}

// MARK: - ScheduleDetailsPresenterInput

extension TestPresenter: TestPresenterInput {
    func presentSomething() {
        
    }
    
}
