//
//  TestWorker.swift
//  CleanSwift
//
//  Created by Phạm Thanh Hải on 10/9/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Lee Nguyen Templates which motivated by CleanSwift templates so
//  you can apply clean architecture to your iOS and Mac projects

import UIKit

class TestWorker
{
  func doSomeWork()
  {
  }
}
