//
//  TestConfigurator.swift
//  CleanSwift
//
//  Created by Phạm Thanh Hải on 10/9/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//  This file was generated by Lee Nguyen Templates which motivated by CleanSwift templates so
//  you can apply clean architecture to your iOS and Mac projects,
import UIKit

class TestConfigurator
{
    // MARK: - Singleton

    static let sharedInstance: TestConfigurator = TestConfigurator()
    
    init() {
        
    }
    
    deinit {
        print("TestConfigurator \(#function)")
    }

    // MARK: - Configuration

    func configure(viewController: TestViewController) {

        let router = TestRouter(viewController: viewController)
        let presenter = TestPresenter(output: viewController)
        let interactor = TestInteractor(output: presenter)
        
        router.dataStore = interactor
        viewController.output = interactor
        viewController.router = router
    }
  
}
