//
//  TestInteractor.swift
//  CleanSwift
//
//  Created by Phạm Thanh Hải on 10/9/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Lee Nguyen Templates which motivated by CleanSwift templates so
//  you can apply clean architecture to your iOS and Mac projects,

import UIKit

protocol TestInteractorInput: TestViewControllerOutput {

    
}

protocol TestInteractorOutput : AnyObject {
    func presentSomething()
}

protocol TestDataStore
{
  //var name: String { get set }
}


final class TestInteractor: TestDataStore {
    
    let output: TestInteractorOutput
    let worker:TestWorker
    
    init(output: TestInteractorOutput, worker: TestWorker = TestWorker()) {
        self.output = output
        self.worker = worker
    }
    
    deinit {
        print("TestInteractor \(#function)")
    }
    
}

extension TestInteractor: TestInteractorInput {
    func resquestSomethings() {
        
    }

}
